import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        {children}

        <ToastContainer
          position="top-center"
          theme="dark"
          draggable
          hideProgressBar
          closeButton={false}
          autoClose={1500}
        />

        <div id="portal-wrapper"></div>
      </body>
    </html>
  );
}
